`timescale 1ns/1ps
//============================================================================
// bit_accuracy_tb.v -- RTL-vs-golden bit-accuracy + ARGMAX harness for
//                      the committed src/glm_matmul_fp8.v
//----------------------------------------------------------------------------
// PURPOSE
//   Drive the COMMITTED glm_matmul_fp8 with a SUITE of representative FP8 tiles
//   (generated by test/bit_accuracy_gen.py, expected outputs computed by the
//   golden tools/glm_fp8_ref.py) and, per tile, assert TWO things:
//
//     (1) BIT-EXACT : c_out == expect.hex (the exact-BFP golden C_bfp).  Proves
//         glm_fp8_ref.py faithfully models the RTL's [128,128]-block FP8 GEMM,
//         so the reference can stand in for the RTL in the error report.
//
//     (2) ARGMAX    : the column chosen by max-logit per output row equals the
//         column the REAL-CONTRACT engine (fp32 accumulator, argmax.hex) chose.
//         This is the binding metric -- the next-token decision a real model
//         makes.  $fatal on ANY argmax divergence.
//
//   Vectors live in +vec=<dir> (default scratchpad/bitacc).  Regenerate with:
//       python3 test/bit_accuracy_gen.py <dir>
//   Tile geometry MUST match the generator: PE_M=2 PE_N=4 KMAX=256 BLK=128.
//============================================================================
module bit_accuracy_tb;
    localparam integer PE_M    = 2;
    localparam integer PE_N    = 4;
    localparam integer KMAX    = 256;
    localparam integer BLK     = 128;
    localparam integer NB      = (KMAX + BLK - 1) / BLK;
    localparam integer KW      = $clog2(KMAX + 1);
    localparam integer MAXTILE = 32;          // memory sizing upper bound (matches gen)

    reg clk = 1'b0;
    always #5 clk = ~clk;

    reg                      rst;
    reg                      start;
    reg  [KW-1:0]            k_len;
    reg                      in_valid;
    reg  [16*PE_M-1:0]       a_col;
    reg  [ 8*PE_N-1:0]       w_row;
    reg  [ 8*PE_M-1:0]       a_shift;
    reg  [16*PE_N*NB-1:0]    w_scale;
    wire                     busy;
    wire                     out_valid;
    wire [16*PE_M*PE_N-1:0]  c_out;

    glm_matmul_fp8 #(.PE_M(PE_M), .PE_N(PE_N), .KMAX(KMAX), .BLK(BLK)) dut (
        .clk(clk), .rst(rst), .start(start), .k_len(k_len),
        .in_valid(in_valid), .a_col(a_col), .w_row(w_row),
        .a_shift(a_shift), .w_scale(w_scale),
        .busy(busy), .out_valid(out_valid), .c_out(c_out)
    );

    // ---- vector memories (packed bus words, $readmemh) ----
    reg [16*PE_M-1:0]       a_mem  [0:MAXTILE*KMAX-1];
    reg [ 8*PE_N-1:0]       w_mem  [0:MAXTILE*KMAX-1];
    reg [ 8*PE_M-1:0]       ash_mem[0:MAXTILE-1];
    reg [16*PE_N*NB-1:0]    ws_mem [0:MAXTILE-1];
    reg [KW-1:0]            kl_mem [0:MAXTILE-1];
    reg [16*PE_M*PE_N-1:0]  exp_mem[0:MAXTILE-1];
    reg [ 8*PE_M-1:0]       am_mem [0:MAXTILE-1];

    integer ntile;
    integer t, k, i, j;
    integer bit_errors, argmax_errors, passed;
    integer rtl_am, real_am;
    reg [15:0] got, want;
    reg [1023:0] vdir;
    integer fd, scanned;

    // ---- bf16 monotonic key for argmax compare (matches python argmax) ----
    // map sign-magnitude bf16 -> monotone unsigned: positives get top bit set,
    // negatives are bitwise inverted.  greater key == greater real value.
    function [15:0] keybf(input [15:0] b);
        keybf = b[15] ? (~b) : (b | 16'h8000);
    endfunction

    // argmax (first-occurrence tie-break) over the PE_N columns of one row of a
    // packed PE_M*PE_N c_out / expect word.
    function integer argmax_row(input [16*PE_M*PE_N-1:0] cw, input integer row);
        integer c, bestc;
        reg [15:0] bestk, kk;
        begin
            bestc = 0;
            bestk = keybf(cw[16*(row*PE_N+0) +: 16]);
            for (c = 1; c < PE_N; c = c + 1) begin
                kk = keybf(cw[16*(row*PE_N+c) +: 16]);
                if (kk > bestk) begin
                    bestk = kk;
                    bestc = c;
                end
            end
            argmax_row = bestc;
        end
    endfunction

    initial begin
        if (!$value$plusargs("vec=%s", vdir)) vdir = "scratchpad/bitacc";

        // tile count
        fd = $fopen({vdir, "/ntile.txt"}, "r");
        if (fd == 0) begin $display("BITACC FAIL: cannot open ntile.txt"); $fatal(1); end
        scanned = $fscanf(fd, "%d", ntile);
        $fclose(fd);
        if (scanned != 1 || ntile <= 0) begin
            $display("BITACC FAIL: bad ntile"); $fatal(1);
        end

        $readmemh({vdir, "/a_col.hex"},  a_mem);
        $readmemh({vdir, "/w_row.hex"},  w_mem);
        $readmemh({vdir, "/ashift.hex"}, ash_mem);
        $readmemh({vdir, "/wscale.hex"}, ws_mem);
        $readmemh({vdir, "/klen.hex"},   kl_mem);
        $readmemh({vdir, "/expect.hex"}, exp_mem);
        $readmemh({vdir, "/argmax.hex"}, am_mem);

        bit_errors    = 0;
        argmax_errors = 0;
        passed        = 0;

        rst      = 1'b1;
        start    = 1'b0;
        in_valid = 1'b0;
        a_col    = {16*PE_M{1'b0}};
        w_row    = {8*PE_N{1'b0}};
        a_shift  = {8*PE_M{1'b0}};
        w_scale  = {16*PE_N*NB{1'b0}};
        k_len    = KMAX[KW-1:0];
        repeat (4) @(posedge clk);
        rst = 1'b0;
        @(posedge clk);

        $display("BITACC: running %0d tiles (PE_M=%0d PE_N=%0d KMAX=%0d BLK=%0d)",
                 ntile, PE_M, PE_N, KMAX, BLK);

        // ====================================================================
        // per-tile loop: each `start` clears the accumulator banks, so no rst
        // needed between tiles.
        // ====================================================================
        for (t = 0; t < ntile; t = t + 1) begin
            // ---- start pulse: latch k_len / a_shift / w_scale, clear banks ----
            @(negedge clk);
            start   = 1'b1;
            a_shift = ash_mem[t];
            w_scale = ws_mem[t];
            k_len   = kl_mem[t];
            @(negedge clk);
            start = 1'b0;

            // ---- stream k_len beats from this tile's slice of the vector mems ----
            for (k = 0; k < kl_mem[t]; k = k + 1) begin
                in_valid = 1'b1;
                a_col    = a_mem[t*KMAX + k];
                w_row    = w_mem[t*KMAX + k];
                @(negedge clk);
            end
            in_valid = 1'b0;
            a_col    = {16*PE_M{1'b0}};
            w_row    = {8*PE_N{1'b0}};

            // ---- wait for the result ----
            k = 0;
            while (!out_valid && k < 100000) begin
                @(posedge clk);
                k = k + 1;
            end
            if (!out_valid) begin
                $display("BITACC FAIL: tile %0d timeout waiting for out_valid", t);
                $fatal(1);
            end

            // ---- (1) bit-exact compare every bf16 element ----
            for (i = 0; i < PE_M; i = i + 1) begin
                for (j = 0; j < PE_N; j = j + 1) begin
                    got  = c_out      [16*(i*PE_N+j) +: 16];
                    want = exp_mem[t] [16*(i*PE_N+j) +: 16];
                    if (got !== want) begin
                        bit_errors = bit_errors + 1;
                        $display("  tile %0d BITEXACT MISMATCH [%0d][%0d]: rtl=%h golden=%h",
                                 t, i, j, got, want);
                    end
                end
            end

            // ---- (2) argmax (next-token decision) compare per row ----
            for (i = 0; i < PE_M; i = i + 1) begin
                rtl_am  = argmax_row(c_out, i);
                real_am = am_mem[t][8*i +: 8];
                if (rtl_am !== real_am) begin
                    argmax_errors = argmax_errors + 1;
                    $display("  tile %0d ARGMAX DIVERGENCE row %0d: rtl->col %0d  real-engine->col %0d",
                             t, i, rtl_am, real_am);
                end
            end

            if (bit_errors == 0 && argmax_errors == 0)
                passed = passed + 1;

            $display("  tile %0d: bit-exact=%s argmax=%s",
                     t,
                     (bit_errors == 0) ? "ok" : "FAIL",
                     (argmax_errors == 0) ? "preserved" : "DIVERGED");

            // hard bar: never let an argmax divergence slip through.
            if (argmax_errors != 0) begin
                $display("BITACC FAIL: %0d argmax divergence(s) -- the real-model next-token decision changed.", argmax_errors);
                $fatal(1);
            end
        end

        // ====================================================================
        // verdict
        // ====================================================================
        if (bit_errors != 0) begin
            $display("BITACC FAIL: %0d bit-exact mismatch(es) over %0d tiles (golden is NOT a faithful RTL model).", bit_errors, ntile);
            $fatal(1);
        end
        if (passed != ntile) begin
            $display("BITACC FAIL: only %0d/%0d tiles passed.", passed, ntile);
            $fatal(1);
        end
        $display("ALL %0d TESTS PASSED  (glm_matmul_fp8 bit-exact to glm_fp8_ref golden; argmax preserved vs the real fp32-acc engine)", ntile);
        $finish;
    end

    // global safety timeout
    initial begin
        #50000000;
        $display("BITACC FAIL: global timeout");
        $fatal(1);
    end
endmodule
